gem "rails", "2.3.9"
gem "yajl-ruby"
gem "rack"
gem "mysql"
gem "database_cleaner"
gem "erubis"
gem "rpx_now"
gem "nokogiri"
gem "hpricot"
gem "whenever"
gem "laco-www-delicious", "0.3.5" # My own version with better API support
gem "css_parser"
gem "mail_style"
gem "adzap-ar_mailer"

group :test do
  gem "pickle"
  gem "factory_girl"
  gem "rspec"
  gem "rspec-rails"
  gem "ruby-debug"
  gem "webrat"
  gem "fakeweb"
  gem "cucumber"
  gem "cucumber-rails"
  gem "rcov"
  gem "mocha"
end

source "http://gemcutter.org"
source "http://gems.github.com"
