gem "rails", "2.3.5"
gem "rack"
gem "mysql"
gem "database_cleaner"
gem "erubis"
gem "rpx_now"
gem "nokogiri"
gem "hpricot"
gem "whenever"
gem "www-delicious"
gem "css_parser"
gem "mail_style"
gem "ar_mailer" # ar_mailer_rails3 for Rails 3

group :test do
  gem "pickle"
  gem "factory_girl"
  gem "rspec"
  gem "rspec-rails"
  gem "ruby-debug"
  gem "webrat"
  gem "fakeweb"
  gem "cucumber"
  gem "cucumber-rails"
  gem "rcov"
  gem "mocha"
end

source "http://gemcutter.org"
source "http://gems.github.com"